/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#00513e",
        "primary-fixed": "#d7e3fc",
        "on-tertiary-fixed-variant": "#653e00",
        "secondary-fixed": "#64fbce",
        "surface-tint": "#535f74",
        "error": "#ba1a1a",
        "secondary-container": "#60f8cb",
        "on-error-container": "#93000a",
        "on-tertiary-fixed": "#2a1700",
        "outline-variant": "#c5c6cd",
        "on-tertiary-container": "#b87500",
        "on-primary-fixed-variant": "#3c475b",
        "tertiary": "#000000",
        "surface-container-lowest": "#ffffff",
        "background": "#fbf8fa",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#ffddb8",
        "inverse-on-surface": "#f3f0f2",
        "on-surface-variant": "#44474c",
        "inverse-surface": "#303032",
        "on-surface": "#1b1b1d",
        "surface-container-low": "#f5f3f5",
        "secondary-fixed-dim": "#3fdeb3",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#101c2e",
        "surface-bright": "#fbf8fa",
        "on-background": "#1b1b1d",
        "surface-variant": "#e4e2e3",
        "secondary": "#006c53",
        "surface-dim": "#dcd9db",
        "tertiary-container": "#2a1700",
        "on-error": "#ffffff",
        "on-primary-container": "#79849b",
        "on-secondary-container": "#007057",
        "surface": "#fbf8fa",
        "on-secondary": "#ffffff",
        "primary-container": "#101c2e",
        "outline": "#75777d",
        "error-container": "#ffdad6",
        "primary": "#000000",
        "on-secondary-fixed": "#002117",
        "surface-container-highest": "#e4e2e3",
        "tertiary-fixed-dim": "#ffb95f",
        "surface-container-high": "#eae7e9",
        "surface-container": "#f0edef",
        "primary-fixed-dim": "#bbc7df",
        "inverse-primary": "#bbc7df",
        "status-safe": "#00C49A",
        "status-safe-dim": "#008f70",
        "status-caution": "#F59E0B",
        "status-caution-dim": "#b47100",
        "status-harmful": "#EF4444",
        "status-harmful-dim": "#c81e1e",
        "hero-navy": "#0F1B2D",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "container-max": "1280px",
        "stack-md": "16px",
        "margin-mobile": "16px",
        "stack-lg": "32px",
        "nav-height": "64px",
        "gutter": "24px",
        "stack-sm": "8px"
      },
      fontFamily: {
        "body-main": ["Manrope", "sans-serif"],
        "h2": ["Manrope", "sans-serif"],
        "h1": ["Manrope", "sans-serif"],
        "body-sm": ["Manrope", "sans-serif"],
        "chemical-name": ["Space Grotesk", "sans-serif"],
        "label-caps": ["Space Grotesk", "sans-serif"]
      },
      fontSize: {
        "body-main": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "h2": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "h1": ["32px", { "lineHeight": "1.2", "fontWeight": "700" }],
        "body-sm": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "chemical-name": ["14px", { "lineHeight": "1.4", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "label-caps": ["12px", { "lineHeight": "1", "fontWeight": "600", "textTransform": "uppercase", "letterSpacing": "0.05em" }]
      },
      boxShadow: {
        "card": "0 1px 4px rgba(0, 0, 0, 0.06)",
        "elevated": "0 4px 24px rgba(0, 0, 0, 0.04)",
        "hero-input": "0 4px 24px rgba(0, 0, 0, 0.2)",
      },
      animation: {
        "fade-in-up": "fadeInUp 0.6s ease-out forwards",
        "fade-in": "fadeIn 0.4s ease-out forwards",
        "slide-down": "slideDown 0.3s ease-out forwards",
        "spin-slow": "spin 1s linear infinite",
        "pulse-slow": "pulse 2s ease-in-out infinite",
      },
      keyframes: {
        fadeInUp: {
          "0%": { opacity: 0, transform: "translateY(20px)" },
          "100%": { opacity: 1, transform: "translateY(0)" },
        },
        fadeIn: {
          "0%": { opacity: 0 },
          "100%": { opacity: 1 },
        },
        slideDown: {
          "0%": { opacity: 0, transform: "translateY(-10px)" },
          "100%": { opacity: 1, transform: "translateY(0)" },
        }
      }
    },
  },
  plugins: [],
}
